### ISSUE TITLE
CANNOT GET HTTP resources

### ISSUE THREAD

**Issue by mousiefasil** [azak-azkaran/cascade#1]
Cascade throws an error when a http site is called e.g.

http://tagesschau.de the following is displayed in the browser:

`proxyconnect tcp: dial tcp: lookup http: no such host`

Cascade log shows the following:

`INFO: 2019/06/17 11:11:30 modeSelector.go:52: Running check on:  https://www.google.de
ERROR: 2019/06/17 11:11:30 modeSelector.go:55: Error while checking, https://www.google.de  ,  Get https://www.google.de: dial tcp: lookup www.google.de: no such host
INFO: 2019/06/17 11:11:30 modeSelector.go:67: Check returns:  false
INFO: 2019/06/17 11:11:30 modeSelector.go:69: Current Mode: CascadeMode
INFO: 2019/06/17 11:11:32 ctx.go:50: [142] INFO: Got request / www.tagesschau.de GET http://www.tagesschau.de/
INFO: 2019/06/17 11:11:32 ctx.go:50: [142] INFO: Sending request GET http://www.tagesschau.de/
INFO: 2019/06/17 11:11:32 ctx.go:50: [142] INFO: error read response www.tagesschau.de proxyconnect tcp: dial tcp: lookup http: no such host:
`

**Comment by azak-azkaran** [comment]
should be fixed with:
[commit](https://github.com/azak-azkaran/cascade/commit/4d31a11a759538a059008286790a3e3a6631b635
)

I can not reproduce the error in the newest version

**Comment by azak-azkaran** [comment]
After some conversation with the reporter, the error was a wrong version
