### ISSUE TITLE
Endpoint SetAutoMode does not work

### ISSUE THREAD

**Issue by mousiefasil** [azak-azkaran/cascade#3]
Deactivating automode other the setAutoMode does not work see figure below:
![cascadesetautomodeissue](https://user-images.githubusercontent.com/36261187/87412650-90672a80-c5c9-11ea-86bb-9275f51fe8eb.PNG)

**Comment by azak-azkaran** [comment]
should be fixed with  7920cd92118dd48824a75da64df3cb1eda2daf9f
